### ISSUE TITLE
Switching to Icicle

### ISSUE THREAD

**Issue by sagebind** [sagebind/slack-client#10]
Switch from React PHP to [Icicle](http://github.com/icicleio/icicle), which is so much easier to work with and so much cooler. Icicle should have a usable websocket package soon, which will be much more actively maintained and less buggy than PHPWS., which was a less-than-ideal dependency anyway.

This will be a major change, and will be bundled with other changes toward a v1.0 release. All React-related code will be removed and replaced with Icicle. Guzzle may also be removed in favor of [`icicleio/http`](https://github.com/icicleio/http).  A name change may also be involved.

*Shameless plug: I'm a member of the Icicle team.* :grinning:

**Comment by david-duncan** [comment]
I see icicle had a websocket component but haven't investigated it yet. Is it mature enough to start experimenting with this?

**Comment by coderstephen** [comment]
@david-duncan Unfortunately the websocket component is server-only and doesn't have a client yet.

**Comment by sagebind** [comment]
Icicle is now transitioning into amphp 2, so this idea is a bust. We shall see if amphp 2 provides a websocket client in the future, and potentially this package may see a transition.
