### ISSUE TITLE
Enabling markdown?

### ISSUE THREAD

**Issue by Repox** [sagebind/slack-client#30]
This might just be something I misunderstood, but I made a message with an attachment like the following, but I just can't seem to get markdown enabled. I tried adding the `mrkdown_in` to the attachment fields (https://api.slack.com/docs/message-formatting), but I haven't gotten it to work yet.

```
    $message = $client->getMessageBuilder()
        ->setText('Ordinary text')
        ->setChannel($channel)
        ->addAttachment(new Attachment('This is my attachment:', 'This *is* _my_ text', "#BADA55", "Pretext with *bold* word", ['mrkdown_in' => ['text', 'pretext', 'fields']]))
        ->create();
```

The markdown is never parsed, when it get's into the channel.

**Comment by bdaroz** [comment]
As a workaround for this... If you have an attachment as `$attachment`:

```$attachment->data['mrkdwn_in'] = ['text', 'pretext', 'fields'];```

Does work as well.
