### ISSUE TITLE
Cant send a message with an attachment

### ISSUE THREAD

**Issue by matansh** [sagebind/slack-client#33]
No mater what i have tried i just cant get this lib to send messages with attachments, some sort of explanation or sample code could be extremely helpfull

**Comment by bdaroz** [comment]
By attachment I assume you mean a message attachment, not a file attachment. If the latter, this is no help....

For each attachment you want to attach to a message, create a new `Attachment` object, let's call it `$attachment`. Check the constructor for the fields you can set. When sending your message, use the MessageBuilder:
```
$mb = $client->getMessageBuilder()
            ->setText($messageText)
            ->setChannel($channel);
```

For each attachment you need to add:
```
$mb = $mb->addAttachment($attachment)
```

In my code I have a "send" function that I pass an array of attachments to, and I walk the array to attach them there.

Finally, create a `Message` object from the builder like so:
```
$message = $mb->create();
```

And send your message off:
```
$client->postMessage($message);
```

**Comment by calonmerc** [comment]
This needs to be documented in the API docs.... took me hours of googling to find this issue that solved my issue. It isn't a standard class implementation and it's frustrating!

**Comment by sagebind** [comment]
@calonmerc There is an example of creating attachments in the README already [here](https://github.com/sagebind/slack-client#advanced-messages).

**Comment by calonmerc** [comment]
That example only shows how to add one attachment, but not multiple.

**Comment by sagebind** [comment]
@calonmerc

```php
$builder = $client->getMessageBuilder()
    ->setText('Hello, all!')
    ->setChannel($someChannelObject)

for ($myThingsToAttach as $title => $text) {
    $builder->addAttachment(new Attachment($title, $text));
}

$message = $builder->create();
```

`addAttachment()` is just a builder mutator method that adds an attachment to the builder object.

**Comment by calonmerc** [comment]
That's my point.... I figured it out AFTER finding this issue, that exact sample needs to be in the docs because it isn't set up as a standard class....

And that code won't work.... the only way I could get it to work would be:
`$builder = $client->getMessageBuilder()
    ->setText('Hello, all!')
    ->setChannel($someChannelObject);

for ($myThingsToAttach as $title => $text) {
    $builder = $builder->addAttachment(new Attachment($title, $text));
}

$message = $builder->create();`

Notice the loop part, that's the only way it would work in any implementation of the code.

**Comment by matansh** [comment]
Hope this thread continues to help people, eventually I needed something very specific so I implemented my own message builder class using guzzle for http requests.
