### ISSUE TITLE
Error Installing on Ubuntu 14.04

### ISSUE THREAD

**Issue by WDC** [sagebind/slack-client#37]
```
  Problem 1
    - Installation request for coderstephen/slack-client ^0.2.5 -> satisfiable by coderstephen/slack-client[v0.2.5].
    - coderstephen/slack-client v0.2.5 requires devristo/phpws dev-master -> satisfiable by devristo/phpws[dev-master] but these conflict with your requirements or minimum-stability.
```

Is there a way I can still use this package?

**Comment by sagebind** [comment]
@WDC Yep, see the installation section in the [README](../blob/master/README.md#installation):

> Please note that the current version has unstable dependencies.
>
>In order to install those dependencies, you can set "minimum-stability" in your composer.json, and recommend that you set "prefer-stable":
>
> ```
> {
>     "minimum-stability": "dev",
>     "prefer-stable": true
> }

**Comment by WDC** [comment]
i tried that, and still no change. Thanks for the quick response!

 ```
 [InvalidArgumentException]
  Could not find package sagebind/slack-client at any version for your minimum-stability (dev). Check the package spelling or your mi
  nimum-stability
```

**Comment by sagebind** [comment]
@WDC The package name is `coderstephen/slack-client`, not `sagebind/slack-client`. It doesn't match GitHub because the username changed.
