### ISSUE TITLE
$client->getChannelById() for Private Messages

### ISSUE THREAD

**Issue by AlexanderMatveev** [sagebind/slack-client#38]
I'm using example code, and this callback newer works with PM's, only with pubic channels:

```php
$client->on('message', function ($data) use ($client) {
$client->getChannelById($data['channel'])->then(function (\Slack\Channel $channel) use ($client) {
print $channel->getId();
```

**Comment by AlexanderMatveev** [comment]
`on('message'` callback works, bot `$client->getChannelById` does not

**Comment by sagebind** [comment]
Try adding an error handler to see if an error was thrown:

```php
$client->on('message', function ($data) use ($client) {
    $client->getChannelById($data['channel'])->then(function (\Slack\Channel $channel) use ($client) {
        print $channel->getId();
    }, function ($error) {
        var_dump($error);
    });
});
```

**Comment by AlexanderMatveev** [comment]
> string(37) "No channel exists for ID 'D2JPB095L'."

And $data is:

> object(Slack\Payload)#53 (1) {
>   ["data":protected]=>
>   array(6) {
>     ["type"]=>
>     string(7) "message"
>     ["channel"]=>
>     string(9) "D2JPB095L"
>     ["user"]=>
>     string(9) "U1H8UJA01"
>     ["text"]=>
>     string(3) "wef"
>     ["ts"]=>
>     string(17) "1475530241.000020"
>     ["team"]=>
>     string(9) "T1H8EQ2SJ"
>   }
> }

**Comment by david-duncan** [comment]
DMs are different from channels

try getDMById

**Comment by AlexanderMatveev** [comment]
The problem is to figure out is message received with `$client->on('message'` was in DM or channel message

**Comment by sagebind** [comment]
@AlexanderMatveev  You can use [ApiClient::getChannelGroupOrDMByID()](http://sagebind.github.io/slack-client/api/class-Slack.ApiClient.html#_getChannelGroupOrDMByID) to get the correct channel type automatically.

**Comment by AlexanderMatveev** [comment]
I see...

```php
if ($id[0] === 'D') {
            return $this->getDMById($id);
        }

        if ($id[0] === 'G') {
            return $this->getGroupById($id);
        }
```

Thanks @sagebind
