### ISSUE TITLE
Random websocket connection closed errors

### ISSUE THREAD

**Issue by mazerab** [sagebind/slack-client#44]
I am running a Python script in a Windows server machine to use the Slack RTM API to listen on new incoming messages addressed to a bot. Based on the message, I write back to the Slack channel where the question was asked. 

Unfortunately, the websocket used by RTM API is randomly getting closed, forcing me to come up with a workaround where I have to call slack_client.rtm_connect() in my except block to re-connect.

This is causing two issues:
1) I don't see a reason why the websocket is getting closed
2) After reconnecting multiple times, the Python script stops listening to messages directed to my bot, forcing me to restart the Python script manually.

Attached is the excerpt from my Python script.

Please let me know if this is a known bug or have a better to handle this type of websocket error.

Thank you in advance for your reply.
Bastien

**Comment by mazerab** [comment]
[sample.py.zip](https://github.com/sagebind/slack-client/files/815460/sample.py.zip)

**Comment by sagebind** [comment]
@mazerab Maybe you meant to create an issue in this repository? https://github.com/slackapi/python-slackclient

This is the Slack client for PHP.

**Comment by mazerab** [comment]
Thank you Stephen,

Slack support advised me to log new issue in wrong github project, sorry for not double-checking.

Here is new issue https://github.com/slackapi/python-slackclient/issues/171

Thank you,
Bastien Mazeran
Premium Support Specialist
Customer Success Services
