### ISSUE TITLE
Php 7 - React TimeoutException

### ISSUE THREAD

**Issue by r4nm4** [sagebind/slack-client#45]
Hi all,
I'm sorry to bother but seems no one have my problem with PHP7.

With PHP 5.6 all good, but after my update to PHP 7,
I started to receive a React Timeout Error.
I can copy and paste the issue, but I don't know how much could be useful.

React\Promise\Timer\TimeoutException: Timed out after 5 seconds in...
#0 [internal function]: React\Promise\Timer\{closure}(Object(React\EventLoop\Timer\Timer))
Next React\Dns\Query\TimeoutException: DNS query for mpmulti-dgb1.slack-msgs.com timed out in...

All my composer library has been updated to the latest version, and honestly I don't know what to do.

Anyone can help me please?
Thank you so much.

Regards

**Comment by akane-tendo** [comment]
Thank you so much for you reply and your great job.
I had a look yesterday on that discussion before open a ticket.
I will continue today to investigate about this issue.
I will let you know.
Thanks

**Comment by akane-tendo** [comment]
Prob was my internal network issue, because right now I have the same problem with any PHP versions.
My apologies for this useless ticket.
Thanks again for your help.
